FROM golang:1.16

ENV http_proxy "http://192.168.0.1:1086"
ENV HTTP_PROXY "http://192.168.0.1:1086"
ENV https_proxy "http://192.168.0.1:1086"
ENV HTTPS_PROXY "http://192.168.0.1:1086"

RUN git clone https://github.com/centrifugal/centrifugo.git $GOPATH/src/centrifugo
WORKDIR $GOPATH/src/centrifugo

COPY main/centrifugo main.go
RUN GO111MODULE=on go mod tidy
RUN GO111MODULE=on go build
RUN chmod +x centrifugo
RUN ./centrifugo genconfig
ENV SERVER_ADDR "http://192.168.0.12:4040"

ENTRYPOINT ["./centrifugo"]