{
 "title": "main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Benchmark Run", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Progress",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "run_progress", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Successful Uploads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "successful_uploads", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Upload Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upload_errors", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(successful_uploads[1m])", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cpu_utilization{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_goroutines\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(storage_reads_total{}[1m])",
     "legendFormat": "reads"
    },
    {
     "expr": "rate(storage_writes_total{}[1m])",
     "legendFormat": "writes"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go_memstats_.+bytes\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "evictions_total_bytes{}", "legendFormat": "RAM total" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "graph",
   "description": "Number of objects in cache",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"cache_.+_size\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cache_dicts_hit / (cache_dicts_hit+cache_dicts_miss)",
     "legendFormat": "cache_dicts_hit_rate"
    },
    {
     "expr": "cache_trees_hit / (cache_trees_hit+cache_trees_miss)",
     "legendFormat": "cache_trees_hit_rate"
    },
    {
     "expr": "cache_segments_hit / (cache_segments_hit+cache_segments_miss)",
     "legendFormat": "cache_segments_hit_rate"
    },
    {
     "expr": "cache_dimensions_hit / (cache_dimensions_hit+cache_dimensions_miss)",
     "legendFormat": "cache_dimensions_hit_rate"
    }
   ]
  },
  {
   "title": "Cache Evictions Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"evictions_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"evictions_count\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cache Write Back Timer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"write_back_timer\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"write_back_count\", instance=\"pyroscope:4040\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "options": {
    "content": "<p style=\"text-align: left; font-weight: bold;\">\n<<< Evictions & Write Back\n</p>\n\nCache objects have two ways of getting persisted:\n* via evictions when there's memory pressure\n* via write-back mechanism that's continiuosly saving data on disk"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Badger Space Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"disk_.+\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Badger Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"storage_.+_read\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Badger Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"storage_.+_write\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Retention",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "retention_timer", "legendFormat": "{{__name__}}" },
    { "expr": "retention_count", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}